repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/Bahjat/pre-commit-golang
    rev: c3086eea8af86847dbdff2e46b85a5fe3c9d9656
    hooks:
    -   id: go-fmt-import
    -   id: go-vet
    -   id: go-lint
